// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMP2tyC0_pdahfIm-bM_lkqWgrJcLWTk',
    appId: '1:913412953470:web:c6e285844f9b4b029d4f2f',
    messagingSenderId: '913412953470',
    projectId: 'persionality-test',
    databaseURL: 'https://persionality-test-default-rtdb.firebaseio.com',
    authDomain: 'persionality-test.firebaseapp.com',
    storageBucket: 'persionality-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5evQspnkshSVsReBW5S4nfmq38IDg7A',
    appId: '1:913412953470:android:845fb51f5b0c4b259d4f2f',
    messagingSenderId: '913412953470',
    projectId: 'persionality-test',
    storageBucket: 'persionality-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKQ7IDrk5YV9Jg54BMp7cNIlCFK5TCog',
    appId: '1:913412953470:ios:533267cabbaf9a469d4f2f',
    messagingSenderId: '913412953470',
    projectId: 'persionality-test',
    storageBucket: 'persionality-test.appspot.com',
    iosBundleId: 'com.example.personalityTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkMP2tyC0_pdahfIm-bM_lkqWgrJcLWTk',
    appId: '1:913412953470:web:47d74183424e4eba9d4f2f',
    messagingSenderId: '913412953470',
    projectId: 'persionality-test',
    authDomain: 'persionality-test.firebaseapp.com',
    storageBucket: 'persionality-test.appspot.com',
  );
}
